### ISSUE TITLE
gdk-sys Cairo Dependency

### ISSUE THREAD

**Issue by jashephe** [gtk-rs/gdk#41] opened 2015-05-17 23:05 UTC
In `Cargo.toml`, the `gdk-sys` dependency is listed as
```
gdk-sys = "^0"
```
Doesn't this mean that it's pulled from [crates.io](https://crates.io/) rather than from the local copy in the repository?  Is that what we want?  Is there some way to say, "Depend on the copy of `gdk-sys` provided in the repository"?

The relevant use case is:  edit `gdk-sys` locally, adding new ffi bindings, then build `gdk` and discover that it's using the version from [crates.io](https://crates.io/).  I know that this can be overridden locally, but if there's a way to change the default behavior, that seems more ergonomic to me.

**Comment by GuillaumeGomez** [comment] 2015-05-17 23:10
The problem is that crates.io and cargo don't allow a crates to have a dependency inside the project. We didn't have the choice on this one.

**Comment by jashephe** [comment] 2015-05-17 23:28
Huh.  Can we file a bug upstream about this?  Or was there some justification for why this isn't possible?

**Comment by GuillaumeGomez** [comment] 2015-05-17 23:30
I asked about that to @acrichto on the irc, he replied that if a library needs a dependency, that dependency has to declared on crates.io, or something similar. It's late and I'm tired. ^^' I advise you to ask him the question directly, it'll be better and you'll have more details.

**Comment by gkoz** [comment] 2015-05-17 23:32
You can [use git-repo](https://github.com/gkoz/rust-gnome-manifest) to make this problem go away. There will be a cargo override out of the box.

**Comment by GuillaumeGomez** [comment] 2015-05-17 23:34
@gkoz: I don't remember why we didn't choose this solution. Well, I'll see that tomorrow.

**Comment by gkoz** [comment] 2015-05-17 23:37
@GuillaumeGomez I'm not sure what you mean by choosing or not. This is mostly how you manage your own working copy. This tool has helped me manage various branches across multiple repos and not go crazy.

**Comment by gkoz** [comment] 2015-05-17 23:43
Also, path dependencies seem to actually be allowed: https://github.com/sfackler/rust-openssl/blob/master/openssl/Cargo.toml#L22

**Comment by jashephe** [comment] 2015-05-17 23:44
I thought I had seen something like that somewhere.  I don't see why that wouldn't work in our case.  Is there any reason why we wouldn't want to do that?

**Comment by GuillaumeGomez** [comment] 2015-05-18 07:58
@jashephe: That's what we wanted to do at first, the command `cargo publish` didn't allow it, that's all.

**Comment by gkoz** [comment] 2015-05-18 09:47
@GuillaumeGomez you may want to ask sfackler how he managed it. At the very least you could just strip out the path line with used in the process of publishing while keeping it in the got.

**Comment by GuillaumeGomez** [comment] 2015-05-18 09:49
@gkoz: I will, please remind it to me, I might forget otherwise...

**Comment by gkoz** [comment] 2015-05-18 11:25
[This post](https://users.rust-lang.org/t/multi-crate-cargo-repositories-best-practices/692/2) makes me think that it should just work if you do it exactly like
```
[dependencies.blahblah]
path = "../blahblah"
version = "x.y.z"
```
The `blahblah` package does have to already be registered on crates.

**Comment by GuillaumeGomez** [comment] 2015-05-18 11:29
Hum... That seems a lot to update for just a sub-dependency...

**Comment by gkoz** [comment] 2015-05-18 11:39
We probably don't need to publish a new version because of this, as it only affects the git checkouts.

**Comment by GuillaumeGomez** [comment] 2015-05-18 12:16
Maybe we should add an explanation on this error in the README ?

**Comment by gkoz** [comment] 2015-05-18 12:46
You don't want to alter the `Cargo.toml`s? Dunno, using the path seems to be idiomatic and expected so explaining the error may not help a lot.

**Comment by GuillaumeGomez** [comment] 2015-05-18 12:48
I like the fact that `*-sys` are in an independant crate. So I don't really know what solution might fit better here...

**Comment by gkoz** [comment] 2015-05-18 12:54
The openssl example above is exactly like that -- two crates in one repo, there's just a bit different directory structure.

**Comment by gkoz** [comment] 2015-05-25 22:07
We probably can't do anything about this because only the current crate would see the `path` dependency while the others might still link to the same crate from crates leading to confusing errors like `expected 'glib::types::Type' found 'glib::types::Type'`.
We may have to make it clearer that the only supported way of using crates from git is to override all of the repos.
This may call for creating a `crates` branch used for publishing with the "crates" `Cargo.toml` version while the master branch would use the git dependencies. At the time of publishing the `master` would be merged into that branch.

**Comment by GuillaumeGomez** [comment] 2015-05-25 22:27
@gkoz: The big come back of the crates branch !

**Comment by jashephe** [comment] 2015-05-25 22:27
Does openssl not have this problem?  Or do they just not care?

**Comment by gkoz** [comment] 2015-05-26 09:03
@GuillaumeGomez this is a little different from tracking nightlies and stable separately, because we don't expect any conflicts when merging from `master`. The workflow would be: merge from master, bump the version, cargo publish.

@jashephe openssl doesn't have five repos each with a sys crate.

**Comment by gkoz** [comment] 2015-10-15 21:54
It seems, we have a satisfactory crate publishing process now.

**Closed by gkoz** 2015-10-15 21:54 UTC
